JAR_PATH="/opt/zimbra/lib/jars/"

CLASSPATH="/opt/zimbra/lib/jars/*:/root/scAgent3.6.0c/plugins/ZIMBRA/:."

export CLASSPATH

JARS="/root/scAgent3.6.0c/plugins/ZIMBRA/ZimbraSnapCreator.jar"
JARS="$JARS:${JAR_PATH}ant-1.7.0-ziputil-patched.jar"
JARS="$JARS:${JAR_PATH}ant-contrib-1.0b1.jar"
JARS="$JARS:${JAR_PATH}ant-tar-patched.jar"
JARS="$JARS:${JAR_PATH}apache-jsieve-0.4-zimbra.jar"
JARS="$JARS:${JAR_PATH}apache-log4j-extras-1.0.jar"
JARS="$JARS:${JAR_PATH}bcprov-jdk15-146.jar"
JARS="$JARS:${JAR_PATH}catalina-ant.jar"
JARS="$JARS:${JAR_PATH}commons-cli-1.2.jar"
JARS="$JARS:${JAR_PATH}commons-codec-1.4.jar"
JARS="$JARS:${JAR_PATH}commons-dbcp-1.4.jar"
JARS="$JARS:${JAR_PATH}commons-fileupload-1.2.1.jar"
JARS="$JARS:${JAR_PATH}commons-httpclient-3.1.jar"
JARS="$JARS:${JAR_PATH}commons-io-1.4.jar"
JARS="$JARS:${JAR_PATH}commons-logging.jar"
JARS="$JARS:${JAR_PATH}commons-pool-1.5.5.jar"
JARS="$JARS:${JAR_PATH}derby.jar"
JARS="$JARS:${JAR_PATH}dom4j-1.5.2.jar"
JARS="$JARS:${JAR_PATH}ehcache-core-2.4.6.jar"
JARS="$JARS:${JAR_PATH}ews.jar"
JARS="$JARS:${JAR_PATH}ganymed-ssh2-build210.jar"
JARS="$JARS:${JAR_PATH}gifencoder.jar"
JARS="$JARS:${JAR_PATH}guava-r09.jar"
JARS="$JARS:${JAR_PATH}ical4j-0.9.16-patched.jar"
JARS="$JARS:${JAR_PATH}icu4j-4.4.2.jar"
JARS="$JARS:${JAR_PATH}jaxen-1.1.1.jar"
JARS="$JARS:${JAR_PATH}jcommon-1.0.16.jar"
JARS="$JARS:${JAR_PATH}jdom.jar"
JARS="$JARS:${JAR_PATH}jetty-6.1.22.z6.jar"
JARS="$JARS:${JAR_PATH}jetty-rewrite-handler-6.1.22.z6.jar"
JARS="$JARS:${JAR_PATH}jetty-util-6.1.22.z6.jar"
JARS="$JARS:${JAR_PATH}jfreechart-1.0.13.jar"
JARS="$JARS:${JAR_PATH}json.jar"
JARS="$JARS:${JAR_PATH}jython-2.5.2.jar"
JARS="$JARS:${JAR_PATH}jzlib.jar"
JARS="$JARS:${JAR_PATH}libidn-1.19.jar"
JARS="$JARS:${JAR_PATH}log4j-1.2.16.jar"
JARS="$JARS:${JAR_PATH}lucene-analyzers-3.0.3.jar"
JARS="$JARS:${JAR_PATH}lucene-core-3.0.3.jar"
JARS="$JARS:${JAR_PATH}lucene-smartcn-3.0.3.jar"
JARS="$JARS:${JAR_PATH}mail.jar"
JARS="$JARS:${JAR_PATH}memcached-2.5.jar"
JARS="$JARS:${JAR_PATH}mina-core-1.1.7-zimbra.jar"
JARS="$JARS:${JAR_PATH}mina-filter-ssl-1.1.7.jar"
JARS="$JARS:${JAR_PATH}mysql-connector-java-5.1.13-bin.jar"
JARS="$JARS:${JAR_PATH}nekohtml.jar"
JARS="$JARS:${JAR_PATH}servlet-api.jar"
JARS="$JARS:${JAR_PATH}slf4j-api-1.6.1.jar"
JARS="$JARS:${JAR_PATH}slf4j-log4j12-1.6.1.jar"
JARS="$JARS:${JAR_PATH}sqlite-jdbc-3.7.5-1.jar"
JARS="$JARS:${JAR_PATH}tnef-1.6.0.jar"
JARS="$JARS:${JAR_PATH}whack.jar"
JARS="$JARS:${JAR_PATH}xercesImpl-2.9.1.jar"
JARS="$JARS:${JAR_PATH}xpp3.jar"
JARS="$JARS:${JAR_PATH}yuicompressor-2.4.2-zimbra.jar"
JARS="$JARS:${JAR_PATH}zimbrabackup.jar"
JARS="$JARS:${JAR_PATH}zimbra-charset.jar"
JARS="$JARS:${JAR_PATH}zimbracommon.jar"
JARS="$JARS:${JAR_PATH}zimbraim.jar"
JARS="$JARS:${JAR_PATH}zimbra-native.jar"
JARS="$JARS:${JAR_PATH}zimbrasoap.jar"
JARS="$JARS:${JAR_PATH}zimbrastore.jar"
JARS="$JARS:${JAR_PATH}zmzimbratozimbramig.jar" 
JARS="$JARS:."

echo $1
echo $2
echo $3
java ZimbraSnapCreator $1 $2 $3


